from typing import Any

class APIMod:
    def __init__(self, acronym: str, settings: dict[str, Any]) -> None: ...
    @property
    def acronym(self) -> str: ...
    @property
    def settings(self) -> dict[str, Any]: ...

def encode(obj: Any) -> bytes: ...
def decode(data: bytes) -> Any: ...
