"""beatmapset: support favourite count

Revision ID: 1178d0758ebf
Revises:
Create Date: 2025-08-01 04:05:09.882800

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "1178d0758ebf"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("beatmapsets", "favourite_count")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "beatmapsets",
        sa.Column(
            "favourite_count", mysql.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    # ### end Alembic commands ###
