"""statistics: remove level_progress

Revision ID: 8bab62d764a5
Revises: 59c9a0827de0
Create Date: 2025-08-13 10:34:03.430039

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "8bab62d764a5"
down_revision: str | Sequence[str] | None = "59c9a0827de0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "lazer_user_statistics",
        "level_current",
        existing_type=mysql.INTEGER(),
        type_=sa.Float(),
        existing_nullable=False,
    )
    op.drop_column("lazer_user_statistics", "level_progress")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "lazer_user_statistics",
        sa.Column("level_progress", mysql.INTEGER(), autoincrement=False, nullable=False),
    )
    op.alter_column(
        "lazer_user_statistics",
        "level_current",
        existing_type=sa.Float(),
        type_=mysql.INTEGER(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
