"""add beatmap_tag


Revision ID: ebaa317ad928
Revises: 24a32515292d
Create Date: 2025-08-29 12:29:23.267557

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "ebaa317ad928"
down_revision: str | Sequence[str] | None = "24a32515292d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "beatmap_tags",
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.Column("beatmap_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("tag_id", "beatmap_id", "user_id"),
    )
    op.create_index(op.f("ix_beatmap_tags_beatmap_id"), "beatmap_tags", ["beatmap_id"], unique=False)
    op.create_index(op.f("ix_beatmap_tags_tag_id"), "beatmap_tags", ["tag_id"], unique=False)
    op.create_index(op.f("ix_beatmap_tags_user_id"), "beatmap_tags", ["user_id"], unique=False)
    op.drop_column("beatmapsets", "ratings")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("beatmapsets", sa.Column("ratings", mysql.JSON(), nullable=True))
    op.drop_index(op.f("ix_beatmap_tags_user_id"), table_name="beatmap_tags")
    op.drop_index(op.f("ix_beatmap_tags_tag_id"), table_name="beatmap_tags")
    op.drop_index(op.f("ix_beatmap_tags_beatmap_id"), table_name="beatmap_tags")
    op.drop_table("beatmap_tags")
    # ### end Alembic commands ###
