"""beatmap: make max_combo nullable

Revision ID: ce29ef0a5674
Revises: 9aa4f7c06824
Create Date: 2025-08-13 15:38:59.797780

"""

from collections.abc import Sequence

from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "ce29ef0a5674"
down_revision: str | Sequence[str] | None = "9aa4f7c06824"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("beatmaps", "max_combo", existing_type=mysql.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("beatmaps", "max_combo", existing_type=mysql.INTEGER(), nullable=False)
    # ### end Alembic commands ###
