"""feat(db): add session verification fields to login_session

Revision ID: 9419272e4c85
Revises: fe8e9f3da298
Create Date: 2025-09-24 00:46:57.367742

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "9419272e4c85"
down_revision: str | Sequence[str] | None = "fe8e9f3da298"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "login_sessions", sa.Column("session_token", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True)
    )
    op.add_column(
        "login_sessions", sa.Column("verification_method", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True)
    )
    op.create_index(op.f("ix_login_sessions_session_token"), "login_sessions", ["session_token"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_login_sessions_session_token"), table_name="login_sessions")
    op.drop_column("login_sessions", "verification_method")
    op.drop_column("login_sessions", "session_token")
    # ### end Alembic commands ###
