"""add table banned_beatmaps

Revision ID: 9f6b27e8ea51
Revises: 951a2188e691
Create Date: 2025-08-15 07:23:25.645360

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "9f6b27e8ea51"
down_revision: str | Sequence[str] | None = "951a2188e691"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "banned_beatmaps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("beatmap_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_banned_beatmaps_beatmap_id"),
        "banned_beatmaps",
        ["beatmap_id"],
        unique=False,
    )
    op.create_index(op.f("ix_banned_beatmaps_id"), "banned_beatmaps", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_banned_beatmaps_id"), table_name="banned_beatmaps")
    op.drop_index(op.f("ix_banned_beatmaps_beatmap_id"), table_name="banned_beatmaps")
    op.drop_table("banned_beatmaps")
    # ### end Alembic commands ###
