"""score: add rx for taiko & catch

Revision ID: 951a2188e691
Revises: 7e9d5e012d37
Create Date: 2025-08-15 04:38:07.595003

"""

from collections.abc import Sequence

from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "951a2188e691"
down_revision: str | Sequence[str] | None = "7e9d5e012d37"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "beatmaps",
        "mode",
        existing_type=mysql.ENUM("OSU", "TAIKO", "FRUITS", "MANIA", "OSURX", "OSUAP", "TAIKORX", "FRUITSRX"),
        nullable=False,
    )
    op.alter_column(
        "best_scores",
        "gamemode",
        existing_type=mysql.ENUM("OSU", "TAIKO", "FRUITS", "MANIA", "OSURX", "OSUAP", "TAIKORX", "FRUITSRX"),
        nullable=False,
    )
    op.alter_column(
        "lazer_user_statistics",
        "mode",
        existing_type=mysql.ENUM("OSU", "TAIKO", "FRUITS", "MANIA", "OSURX", "OSUAP", "TAIKORX", "FRUITSRX"),
        nullable=False,
    )
    op.alter_column(
        "lazer_users",
        "playmode",
        existing_type=mysql.ENUM("OSU", "TAIKO", "FRUITS", "MANIA", "OSURX", "OSUAP", "TAIKORX", "FRUITSRX"),
        nullable=False,
    )
    op.alter_column(
        "score_tokens",
        "ruleset_id",
        existing_type=mysql.ENUM("OSU", "TAIKO", "FRUITS", "MANIA", "OSURX", "OSUAP", "TAIKORX", "FRUITSRX"),
        nullable=False,
    )
    op.alter_column(
        "scores",
        "gamemode",
        existing_type=mysql.ENUM("OSU", "TAIKO", "FRUITS", "MANIA", "OSURX", "OSUAP", "TAIKORX", "FRUITSRX"),
        nullable=False,
    )
    op.alter_column(
        "total_score_best_scores",
        "gamemode",
        existing_type=mysql.ENUM("OSU", "TAIKO", "FRUITS", "MANIA", "OSURX", "OSUAP", "TAIKORX", "FRUITSRX"),
        nullable=False,
    )
    op.alter_column(
        "rank_history",
        "mode",
        existing_type=mysql.ENUM("OSU", "TAIKO", "FRUITS", "MANIA", "OSURX", "OSUAP", "TAIKORX", "FRUITSRX"),
        nullable=False,
    )
    op.alter_column(
        "rank_top",
        "mode",
        existing_type=mysql.ENUM("OSU", "TAIKO", "FRUITS", "MANIA", "OSURX", "OSUAP", "TAIKORX", "FRUITSRX"),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "beatmaps",
        "mode",
        existing_type=mysql.ENUM("OSU", "TAIKO", "FRUITS", "MANIA", "OSURX", "OSUAP"),
        nullable=False,
    )
    op.alter_column(
        "best_scores",
        "gamemode",
        existing_type=mysql.ENUM("OSU", "TAIKO", "FRUITS", "MANIA", "OSURX", "OSUAP"),
        nullable=False,
    )
    op.alter_column(
        "lazer_user_statistics",
        "mode",
        existing_type=mysql.ENUM("OSU", "TAIKO", "FRUITS", "MANIA", "OSURX", "OSUAP"),
        nullable=False,
    )
    op.alter_column(
        "lazer_users",
        "playmode",
        existing_type=mysql.ENUM("OSU", "TAIKO", "FRUITS", "MANIA", "OSURX", "OSUAP"),
        nullable=False,
    )
    op.alter_column(
        "score_tokens",
        "ruleset_id",
        existing_type=mysql.ENUM("OSU", "TAIKO", "FRUITS", "MANIA", "OSURX", "OSUAP"),
        nullable=False,
    )
    op.alter_column(
        "scores",
        "gamemode",
        existing_type=mysql.ENUM("OSU", "TAIKO", "FRUITS", "MANIA", "OSURX", "OSUAP"),
        nullable=False,
    )
    op.alter_column(
        "total_score_best_scores",
        "gamemode",
        existing_type=mysql.ENUM("OSU", "TAIKO", "FRUITS", "MANIA", "OSURX", "OSUAP"),
        nullable=False,
    )
    op.alter_column(
        "rank_top",
        "mode",
        existing_type=mysql.ENUM("OSU", "TAIKO", "FRUITS", "MANIA", "OSURX", "OSUAP", "TAIKORX", "FRUITSRX"),
        nullable=False,
    )
    op.alter_column(
        "rank_top",
        "mode",
        existing_type=mysql.ENUM("OSU", "TAIKO", "FRUITS", "MANIA", "OSURX", "OSUAP", "TAIKORX", "FRUITSRX"),
        nullable=False,
    )
    # ### end Alembic commands ###
