"""score: add maximum_statistics

Revision ID: 881ac7ca01d5
Revises: 198227d190b8
Create Date: 2025-08-13 03:54:12.283468

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "881ac7ca01d5"
down_revision: str | Sequence[str] | None = "198227d190b8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("scores", sa.Column("maximum_statistics", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scores", "maximum_statistics")
    # ### end Alembic commands ###
