"""room: add channel_id

Revision ID: df9f725a077c
Revises: dd33d89aa2c2
Create Date: 2025-08-16 08:05:28.748265

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "df9f725a077c"
down_revision: str | Sequence[str] | None = "dd33d89aa2c2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("chat_silence_users", "user_id", existing_type=mysql.BIGINT(), nullable=True)
    op.alter_column("chat_silence_users", "banned_at", existing_type=mysql.DATETIME(), nullable=True)
    op.create_index(op.f("ix_chat_silence_users_id"), "chat_silence_users", ["id"], unique=False)
    op.add_column("rooms", sa.Column("channel_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rooms", "channel_id")
    op.drop_index(op.f("ix_chat_silence_users_id"), table_name="chat_silence_users")
    op.alter_column(
        "chat_silence_users",
        "banned_at",
        existing_type=mysql.DATETIME(),
        nullable=False,
    )
    op.alter_column("chat_silence_users", "user_id", existing_type=mysql.BIGINT(), nullable=False)
    # ### end Alembic commands ###
