"""auth: add refresh_token_expires_at

Revision ID: 7fe1319250c5
Revises: 72a9b8f3f863
Create Date: 2025-10-02 10:50:21.169065

"""

from collections.abc import Sequence
from datetime import datetime, timedelta

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "7fe1319250c5"
down_revision: str | Sequence[str] | None = "72a9b8f3f863"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("oauth_tokens", sa.Column("refresh_token_expires_at", sa.DateTime(), nullable=True))
    op.create_index(op.f("ix_oauth_tokens_expires_at"), "oauth_tokens", ["expires_at"], unique=False)
    expires_at = datetime.now() + timedelta(days=15)
    expires_at_str = expires_at.strftime("%Y-%m-%d %H:%M:%S")
    op.execute(f"UPDATE oauth_tokens SET refresh_token_expires_at = '{expires_at_str}'")  # noqa: S608
    op.create_index(
        op.f("ix_oauth_tokens_refresh_token_expires_at"), "oauth_tokens", ["refresh_token_expires_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_oauth_tokens_refresh_token_expires_at"), table_name="oauth_tokens")
    op.drop_index(op.f("ix_oauth_tokens_expires_at"), table_name="oauth_tokens")
    op.drop_column("oauth_tokens", "refresh_token_expires_at")
    # ### end Alembic commands ###
