"""feat(db): add password column to rooms table

Revision ID: 57bacf936413
Revises: 178873984b22
Create Date: 2025-08-23 18:45:03.009632

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "57bacf936413"
down_revision: str | Sequence[str] | None = "178873984b22"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("rooms", sa.Column("password", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rooms", "password")
    # ### end Alembic commands ###
