"""auth: add v1 keys table

Revision ID: 7e9d5e012d37
Revises: ce29ef0a5674
Create Date: 2025-08-14 08:39:51.725121

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "7e9d5e012d37"
down_revision: str | Sequence[str] | None = "ce29ef0a5674"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "v1_api_keys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("owner_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["lazer_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_v1_api_keys_key"), "v1_api_keys", ["key"], unique=False)
    op.create_index(op.f("ix_v1_api_keys_name"), "v1_api_keys", ["name"], unique=False)
    op.create_index(op.f("ix_v1_api_keys_owner_id"), "v1_api_keys", ["owner_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("v1_api_keys")
    # ### end Alembic commands ###
