"""score: add processed

Revision ID: 34a563187e47
Revises: 3f890a76f036
Create Date: 2025-08-24 15:06:37.226068

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "34a563187e47"
down_revision: str | Sequence[str] | None = "3f890a76f036"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("scores", sa.Column("processed", sa.Boolean(), nullable=False, default=1, server_default="1"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scores", "processed")
    # ### end Alembic commands ###
