"""convert Event.event_payload from str to json

Revision ID: f785165a5c0b
Revises: 881ac7ca01d5
Create Date: 2025-08-13 06:02:11.911557

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "f785165a5c0b"
down_revision: str | Sequence[str] | None = "881ac7ca01d5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "beatmaps",
        "mode",
        existing_type=mysql.ENUM("OSU", "TAIKO", "FRUITS", "MANIA", "OSURX", "OSUAP"),
        nullable=False,
    )
    op.alter_column(
        "best_scores",
        "gamemode",
        existing_type=mysql.ENUM("OSU", "TAIKO", "FRUITS", "MANIA", "OSURX", "OSUAP"),
        nullable=False,
    )
    op.alter_column(
        "lazer_user_statistics",
        "mode",
        existing_type=mysql.ENUM("OSU", "TAIKO", "FRUITS", "MANIA", "OSURX", "OSUAP"),
        nullable=False,
    )
    op.alter_column(
        "lazer_users",
        "playmode",
        existing_type=mysql.ENUM("OSU", "TAIKO", "FRUITS", "MANIA", "OSURX", "OSUAP"),
        nullable=False,
    )
    op.alter_column("monthly_playcounts", "count", existing_type=mysql.INTEGER(), nullable=False)
    op.alter_column(
        "score_tokens",
        "ruleset_id",
        existing_type=mysql.ENUM("OSU", "TAIKO", "FRUITS", "MANIA", "OSURX", "OSUAP"),
        nullable=False,
    )
    op.alter_column(
        "scores",
        "gamemode",
        existing_type=mysql.ENUM("OSU", "TAIKO", "FRUITS", "MANIA", "OSURX", "OSUAP"),
        nullable=False,
    )
    op.alter_column(
        "total_score_best_scores",
        "gamemode",
        existing_type=mysql.ENUM("OSU", "TAIKO", "FRUITS", "MANIA", "OSURX", "OSUAP"),
        nullable=False,
    )
    op.alter_column(
        "user_events",
        "event_payload",
        existing_type=mysql.VARCHAR(length=255),
        type_=sa.JSON(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_events",
        "event_payload",
        existing_type=sa.JSON(),
        type_=mysql.VARCHAR(length=255),
        nullable=False,
    )
    op.alter_column(
        "total_score_best_scores",
        "gamemode",
        existing_type=mysql.ENUM("OSU", "TAIKO", "FRUITS", "MANIA", "OSURX", "OSUAP"),
        nullable=True,
    )
    op.alter_column(
        "scores",
        "gamemode",
        existing_type=mysql.ENUM("OSU", "TAIKO", "FRUITS", "MANIA", "OSURX", "OSUAP"),
        nullable=True,
    )
    op.alter_column(
        "score_tokens",
        "ruleset_id",
        existing_type=mysql.ENUM("OSU", "TAIKO", "FRUITS", "MANIA", "OSURX", "OSUAP"),
        nullable=True,
    )
    op.alter_column("monthly_playcounts", "count", existing_type=mysql.INTEGER(), nullable=True)
    op.alter_column(
        "lazer_users",
        "playmode",
        existing_type=mysql.ENUM("OSU", "TAIKO", "FRUITS", "MANIA", "OSURX", "OSUAP"),
        nullable=True,
    )
    op.alter_column(
        "lazer_user_statistics",
        "mode",
        existing_type=mysql.ENUM("OSU", "TAIKO", "FRUITS", "MANIA", "OSURX", "OSUAP"),
        nullable=True,
    )
    op.alter_column(
        "best_scores",
        "gamemode",
        existing_type=mysql.ENUM("OSU", "TAIKO", "FRUITS", "MANIA", "OSURX", "OSUAP"),
        nullable=True,
    )
    op.alter_column(
        "beatmaps",
        "mode",
        existing_type=mysql.ENUM("OSU", "TAIKO", "FRUITS", "MANIA", "OSURX", "OSUAP"),
        nullable=True,
    )
    # ### end Alembic commands ###
