"""login_sessions: remove session_token & add token_id

Revision ID: fe8e9f3da298
Revises: 15e3a9a05b67
Create Date: 2025-09-21 02:30:58.233846

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "fe8e9f3da298"
down_revision: str | Sequence[str] | None = "15e3a9a05b67"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("login_sessions", sa.Column("token_id", sa.Integer(), nullable=True))
    op.drop_index(op.f("ix_login_sessions_session_token"), table_name="login_sessions")
    op.create_index(op.f("ix_login_sessions_token_id"), "login_sessions", ["token_id"], unique=False)
    op.create_foreign_key(None, "login_sessions", "oauth_tokens", ["token_id"], ["id"], ondelete="SET NULL")
    op.drop_column("login_sessions", "session_token")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("login_sessions", sa.Column("session_token", mysql.VARCHAR(length=255), nullable=True))
    connection = op.get_bind()
    connection.execute(
        sa.text("""
            UPDATE login_sessions
            SET session_token = CONCAT('migrated_', id, '_', UNIX_TIMESTAMP(), '_', RAND())
            WHERE session_token IS NULL
        """)
    )
    op.alter_column("login_sessions", "session_token", nullable=False, type_=mysql.VARCHAR(length=255))
    op.create_index(op.f("ix_login_sessions_session_token"), "login_sessions", ["session_token"], unique=True)

    op.drop_constraint(op.f("login_sessions_ibfk_1"), "login_sessions", type_="foreignkey")
    op.drop_index(op.f("ix_login_sessions_token_id"), table_name="login_sessions")
    op.drop_column("login_sessions", "token_id")
    # ### end Alembic commands ###
