"""score: support pin score

Revision ID: 319e5f841dcf
Revises: 19cdc9ce4dcb
Create Date: 2025-08-10 14:07:51.749025

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "319e5f841dcf"
down_revision: str | Sequence[str] | None = "19cdc9ce4dcb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("scores", sa.Column("pinned_order", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scores", "pinned_order")
    # ### end Alembic commands ###
