"""add id data

Revision ID: 3f890a76f036
Revises: 8d2af11343b9
Create Date: 2025-08-24 04:00:02.063347

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "3f890a76f036"
down_revision: str | Sequence[str] | None = "57bacf936413"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f("ix_lazer_user_achievements_achievement_id"), table_name="lazer_user_achievements")
    # op.drop_index(op.f("uq_user_achievement"), table_name="lazer_user_achievements")
    op.add_column(
        "room_playlists", sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True)
    )
    op.add_column(
        "room_playlists", sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("room_playlists", "updated_at")
    op.drop_column("room_playlists", "created_at")
    op.create_index(op.f("uq_user_achievement"), "lazer_user_achievements", ["user_id", "achievement_id"], unique=True)
    op.create_index(
        op.f("ix_lazer_user_achievements_achievement_id"), "lazer_user_achievements", ["achievement_id"], unique=False
    )
    # ### end Alembic commands ###
