"""session: add device_id to LoginSession

Revision ID: 9556cd2ec11f
Revises: 7fe1319250c5
Create Date: 2025-10-02 11:03:09.803140

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "9556cd2ec11f"
down_revision: str | Sequence[str] | None = "7fe1319250c5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("login_sessions", sa.Column("device_id", sa.BigInteger(), nullable=True))
    op.create_index(op.f("ix_login_sessions_device_id"), "login_sessions", ["device_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("login_sessions", "device_id")
    # ### end Alembic commands ###
