"""beatmap: add indexes

Revision ID: 59c9a0827de0
Revises: 881ac7ca01d5
Create Date: 2025-08-13 07:07:52.506510

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "59c9a0827de0"
down_revision: str | Sequence[str] | None = "f785165a5c0b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_beatmaps_beatmap_status"), "beatmaps", ["beatmap_status"], unique=False)
    op.create_index(
        op.f("ix_beatmaps_difficulty_rating"),
        "beatmaps",
        ["difficulty_rating"],
        unique=False,
    )
    op.create_index(op.f("ix_beatmaps_last_updated"), "beatmaps", ["last_updated"], unique=False)
    op.create_index(op.f("ix_beatmaps_user_id"), "beatmaps", ["user_id"], unique=False)
    op.create_index(op.f("ix_beatmaps_version"), "beatmaps", ["version"], unique=False)
    op.create_index(
        op.f("ix_beatmapsets_beatmap_genre"),
        "beatmapsets",
        ["beatmap_genre"],
        unique=False,
    )
    op.create_index(
        op.f("ix_beatmapsets_beatmap_language"),
        "beatmapsets",
        ["beatmap_language"],
        unique=False,
    )
    op.create_index(
        op.f("ix_beatmapsets_beatmap_status"),
        "beatmapsets",
        ["beatmap_status"],
        unique=False,
    )
    op.create_index(op.f("ix_beatmapsets_creator"), "beatmapsets", ["creator"], unique=False)
    op.create_index(
        op.f("ix_beatmapsets_last_updated"),
        "beatmapsets",
        ["last_updated"],
        unique=False,
    )
    op.create_index(op.f("ix_beatmapsets_play_count"), "beatmapsets", ["play_count"], unique=False)
    op.create_index(op.f("ix_beatmapsets_ranked_date"), "beatmapsets", ["ranked_date"], unique=False)
    op.create_index(op.f("ix_beatmapsets_storyboard"), "beatmapsets", ["storyboard"], unique=False)
    op.create_index(
        op.f("ix_beatmapsets_submitted_date"),
        "beatmapsets",
        ["submitted_date"],
        unique=False,
    )
    op.create_index(op.f("ix_beatmapsets_title"), "beatmapsets", ["title"], unique=False)
    op.create_index(
        op.f("ix_beatmapsets_title_unicode"),
        "beatmapsets",
        ["title_unicode"],
        unique=False,
    )
    op.create_index(op.f("ix_beatmapsets_track_id"), "beatmapsets", ["track_id"], unique=False)
    op.create_index(op.f("ix_beatmapsets_user_id"), "beatmapsets", ["user_id"], unique=False)
    op.create_index(op.f("ix_beatmapsets_video"), "beatmapsets", ["video"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_beatmapsets_video"), table_name="beatmapsets")
    op.drop_index(op.f("ix_beatmapsets_user_id"), table_name="beatmapsets")
    op.drop_index(op.f("ix_beatmapsets_track_id"), table_name="beatmapsets")
    op.drop_index(op.f("ix_beatmapsets_title_unicode"), table_name="beatmapsets")
    op.drop_index(op.f("ix_beatmapsets_title"), table_name="beatmapsets")
    op.drop_index(op.f("ix_beatmapsets_submitted_date"), table_name="beatmapsets")
    op.drop_index(op.f("ix_beatmapsets_storyboard"), table_name="beatmapsets")
    op.drop_index(op.f("ix_beatmapsets_ranked_date"), table_name="beatmapsets")
    op.drop_index(op.f("ix_beatmapsets_play_count"), table_name="beatmapsets")
    op.drop_index(op.f("ix_beatmapsets_last_updated"), table_name="beatmapsets")
    op.drop_index(op.f("ix_beatmapsets_creator"), table_name="beatmapsets")
    op.drop_index(op.f("ix_beatmapsets_beatmap_status"), table_name="beatmapsets")
    op.drop_index(op.f("ix_beatmapsets_beatmap_language"), table_name="beatmapsets")
    op.drop_index(op.f("ix_beatmapsets_beatmap_genre"), table_name="beatmapsets")
    op.drop_index(op.f("ix_beatmaps_version"), table_name="beatmaps")
    op.drop_index(op.f("ix_beatmaps_user_id"), table_name="beatmaps")
    op.drop_index(op.f("ix_beatmaps_last_updated"), table_name="beatmaps")
    op.drop_index(op.f("ix_beatmaps_difficulty_rating"), table_name="beatmaps")
    op.drop_index(op.f("ix_beatmaps_beatmap_status"), table_name="beatmaps")
    # ### end Alembic commands ###
