"""sync: add beatmap sync table

Revision ID: 2885978490dc
Revises: dc2087561edf
Create Date: 2025-10-01 12:19:50.485318

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "2885978490dc"
down_revision: str | Sequence[str] | None = "dc2087561edf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "beatmapsync",
        sa.Column("beatmapset_id", sa.Integer(), nullable=False),
        sa.Column("beatmaps", sa.JSON(), nullable=True),
        sa.Column(
            "beatmap_status",
            sa.Enum(
                "GRAVEYARD", "WIP", "PENDING", "RANKED", "APPROVED", "QUALIFIED", "LOVED", name="beatmaprankstatus"
            ),
            nullable=False,
        ),
        sa.Column("consecutive_no_change", sa.Integer(), nullable=False),
        sa.Column("next_sync_time", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["beatmapset_id"],
            ["beatmapsets.id"],
        ),
        sa.PrimaryKeyConstraint("beatmapset_id"),
    )
    op.create_index(op.f("ix_beatmapsync_beatmap_status"), "beatmapsync", ["beatmap_status"], unique=False)
    op.create_index(op.f("ix_beatmapsync_next_sync_time"), "beatmapsync", ["next_sync_time"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("beatmapsync")
    # ### end Alembic commands ###
